site_name: FLaP
repo_url: https://github.com/fchauvel/flap
docs_dir: docs
pages:
 - "Home": index.md
 - "User Guide":
   - "Installation": installation.md
   - "Usage Example": example.md
   - "Supported Commands": features.md
 - "Known Caveats": caveats.md
 - "Contributing":
   - "Reporting Bugs": reporting_issues.md
   - "Coding": getting_ready.md
   - "Testing": testing.md
   - "Releasing": releasing.md
theme: flatly