site_name: FLaP
repo_url: https://github.com/fchauvel/flap
docs_dir: docs
pages:
 - "Home": index.md
 - "User Guide":
   - "Installation": installation.md
   - "Usage Example": example.md
   - "Supported Commands": features.md
 - Contributing: contributing.md
theme: flatly